server:
  port: 8089

  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: team3-booksearch-worker

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: "nhnacademy123!"

  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 60s
    connection-timeout: 5s

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 379

  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team3?serverTimezone=Asia/Seoul
    username: project_be12_team3
    password: Vu52gc0i(mNxDJyI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    main: team3.booksearch.exchange
    retry: team3.booksearch.retry.dlx
    dlx: team3.booksearch.dlx
  queue:
    book-upsert: team3.booksearch.book.upsert.queue
    book-delete: team3.booksearch.book.delete.queue

  routing:
    book-upsert: team3.booksearch.book.upsert
    book-upsert-retry: team3.booksearch.book.upsert.retry
    book-upsert-fail: team3.booksearch.book.upsert.fail

    book-delete: team3.booksearch.book.delete
    book-delete-retry: team3.booksearch.book.delete.retry
    book-delete-fail: team3.booksearch.book.delete.fail

app:
  ai:
    embedding-url: http://ollama.java21.net/api/embeddings
    reranker-url: http://reranker.java21.net/rerank
    gemini-api-key: AIzaSyAPjRTWLiLXhJBCiCKoCNi3aPVMNGkU4go
    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  batch:
    size: 1000

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.listener: INFO
    org.springframework.web.reactive.function.client: INFO
