spring:
  application:
    name: booksearch-worker

  rabbitmq:
    host: s4.java21.net
    port: 5672
    username: admin
    password: "nhnacademy123!"

  elasticsearch:
    uris: http://s4.java21.net:9200
    username: elastic
    password: nhnacademy123!
    socket-timeout: 60s
    connection-timeout: 5s

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: '*N2vya7H@muDTwdNMR!'
      database: 379

  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be12_team3?serverTimezone=Asia/Seoul
    username: project_be12_team3
    password: Vu52gc0i(mNxDJyI
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false


server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: team3.booksearch.exchange

  routing:
    key: team3.booksearch.ai.analysis

  queue:
    name: team3.booksearch.ai.analysis.queue.v1

  retry:
    exchange:
      name: team3.booksearch.ai.analysis.retry.exchange.v1
    routing:
      key: team3.booksearch.ai.analysis.retry.v1
    queue:
      name: team3.booksearch.ai.analysis.retry.queue.v1
    delay-ms: 10000
    max-attempts: 3

  dlx:
    name: team3.booksearch.ai.analysis.dlx
  dlq:
    name: team3.booksearch.ai.analysis.dlq
  dlq-routing:
    key: team3.booksearch.ai.analysis.dlq

app:
  ai:
    embedding-url: http://ollama.java21.net/api/embeddings
    reranker-url: http://reranker.java21.net/rerank
    gemini-api-key: AIzaSyAPjRTWLiLXhJBCiCKoCNi3aPVMNGkU4go
    gemini-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  batch:
    size: 1000

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.listener: INFO
    org.springframework.web.reactive.function.client: INFO
